package fusion

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
)

// GenerateGoAggregator emits the deterministic source-level fusion wrapper.
// Each imported package implements: func Register([]byte) error. Config is an
// ABI envelope owned by the packages; a later ABI can add per-member scoping
// without making the build backend dependent on application manifests.
func GenerateGoAggregator(recipe Recipe) ([]byte, error) {
	canonicalizeRecipe(&recipe)
	if recipe.SchemaVersion == RecipeSchemaV2 {
		return generateGoAggregatorV2(recipe)
	}
	if recipe.SchemaVersion != RecipeSchemaV1 {
		return nil, fmt.Errorf("unsupported fusion recipe schema %q", recipe.SchemaVersion)
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by Pulp fusion; DO NOT EDIT.\npackage main\n\nimport (\n")
	source.WriteString("\t\"github.com/BananaLabs-OSS/Fiber/pulp\"\n")
	for i, member := range recipe.Members {
		if err := validateSource(member.Source); err != nil {
			return nil, fmt.Errorf("member %q source: %w", member.Name, err)
		}
		if member.Source.Entrypoint != "Register" {
			return nil, fmt.Errorf("member %q entrypoint must be Register for %s", member.Name, RecipeSchemaV1)
		}
		fmt.Fprintf(&source, "\tm%03d %s\n", i, strconv.Quote(member.Source.ImportPath))
	}
	source.WriteString(")\n\nfunc init() {\n\tpulp.OnInit(func(config []byte) error {\n")
	for i := range recipe.Members {
		fmt.Fprintf(&source, "\t\tif err := m%03d.Register(config); err != nil { return err }\n", i)
	}
	source.WriteString("\t\treturn nil\n\t})\n}\n\nfunc main() {}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated fusion source: %w", err)
	}
	return formatted, nil
}

func generateGoAggregatorV2(recipe Recipe) ([]byte, error) {
	if recipe.ABI != MemberABIV2 {
		return nil, fmt.Errorf("unsupported fusion v2 ABI %q", recipe.ABI)
	}
	if err := validateBuildRecipe(recipe); err != nil {
		return nil, err
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by Pulp fusion; DO NOT EDIT.\npackage main\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"github.com/BananaLabs-OSS/Fiber/pulp\"\n")
	for i, member := range recipe.Members {
		fmt.Fprintf(&source, "\tm%03d %s\n", i, strconv.Quote(member.Source.ImportPath))
	}
	source.WriteString(")\n\ntype memberHooks struct {\n\tname string\n\tinit func([]byte) error\n\tshutdown func() error\n\tsnapshot func() ([]byte, error)\n\trestore func([]byte) error\n\tconfig []byte\n\tsnapshotable bool\n}\n\nvar members []memberHooks\nvar registrationErr error\n\nfunc init() {\n")
	for i, member := range recipe.Members {
		fmt.Fprintf(&source, "\t{\n\t\tinitFn, shutdownFn, callFn, snapshotFn, restoreFn, err := m%03d.RegisterV2(%s, %s, %#v, %#v)\n", i, strconv.Quote(member.Name), strconv.Quote(member.Version), member.Providers, member.Capabilities)
		fmt.Fprintf(&source, "\t\tif err != nil { registrationErr = fmt.Errorf(\"fusion member %%q register: %%w\", %s, err) } else {\n", strconv.Quote(member.Name))
		fmt.Fprintf(&source, "\t\t\tmembers = append(members, memberHooks{name:%s, init:initFn, shutdown:shutdownFn, snapshot:snapshotFn, restore:restoreFn, config:%#v, snapshotable:%t})\n", strconv.Quote(member.Name), member.Config, member.Snapshotable)
		for _, provider := range member.Providers {
			fmt.Fprintf(&source, "\t\t\tpulp.Provide(%s, func(payload []byte) ([]byte,error) { if callFn == nil { return nil, fmt.Errorf(\"fusion member %%q has no call handler\", %s) }; out, err := callFn(%s, payload); if err != nil { return nil, fmt.Errorf(\"fusion member %%q call %s: %%w\", %s, err) }; return out,nil })\n", strconv.Quote(provider), strconv.Quote(member.Name), strconv.Quote(provider), provider, strconv.Quote(member.Name))
		}
		source.WriteString("\t\t}\n\t}\n")
	}
	source.WriteString("\tpulp.OnInit(func(_ []byte) error {\n\t\tif registrationErr != nil { return registrationErr }\n\t\tinitialized := 0\n\t\tfor i := range members { if members[i].init == nil { return fmt.Errorf(\"fusion member %q has no init hook\", members[i].name) }; if err := members[i].init(members[i].config); err != nil { for j:=initialized-1;j>=0;j-- { if members[j].shutdown != nil { _ = members[j].shutdown() } }; return fmt.Errorf(\"fusion member %q init: %w\", members[i].name,err) }; initialized++ }\n\t\treturn nil\n\t})\n\tpulp.OnShutdown(func() error { var first error; for i:=len(members)-1;i>=0;i-- { if members[i].shutdown == nil { continue }; if err:=members[i].shutdown();err!=nil && first==nil { first=fmt.Errorf(\"fusion member %q shutdown: %w\",members[i].name,err) } }; return first })\n\tpulp.OnSnapshot(func() ([]byte,error) { parts:=map[string][]byte{}; for _,m:=range members { if !m.snapshotable { continue }; if m.snapshot==nil { return nil,fmt.Errorf(\"fusion member %q has no snapshot hook\",m.name) }; b,err:=m.snapshot();if err!=nil{return nil,fmt.Errorf(\"fusion member %q snapshot: %w\",m.name,err)};parts[m.name]=b }; return json.Marshal(parts) })\n\tpulp.OnRestore(func(payload []byte) error { var parts map[string][]byte;if err:=json.Unmarshal(payload,&parts);err!=nil{return fmt.Errorf(\"decode fusion snapshot: %w\",err)};for _,m:=range members { if !m.snapshotable { continue };b,ok:=parts[m.name];if !ok{return fmt.Errorf(\"snapshot partition missing fusion member %q\",m.name)};if m.restore==nil{return fmt.Errorf(\"fusion member %q has no restore hook\",m.name)};if err:=m.restore(b);err!=nil{return fmt.Errorf(\"fusion member %q restore: %w\",m.name,err)} };return nil })\n}\n\nfunc main() {}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated fusion v2 source: %w\n%s", err, source.String())
	}
	return formatted, nil
}
