// Code generated by witcell. DO NOT EDIT.
// Fiber-integrated variant: the pulp_alloc/free pin table, pulp_init/step/
// shutdown, and pulp_on_call dispatch all come from the imported Fiber `pulp`
// package. This file adds ONLY the canonical-ABI glue: request LIFT, result
// LOWER (pinned via pulp.Alloc), the return-tree free exported as
// pulp_post_return, and registration of the typed handler via pulp.ProvideRaw.
package main

import (
	"math"
	"unsafe"

	"github.com/BananaLabs-OSS/Fiber/pulp"
)

func main() {}

// Register the canonical-ABI handler alongside any msgpack Provide handlers.
// Fiber's dispatchOnCall routes "resolve" here (raw path) and leaves every
// other name on the msgpack path.
func init() {
	pulp.ProvideRaw("resolve", rawResolve)
}

// probe_alloc_live exposes Fiber's alloc-table pin count so a host test can
// assert the response tree returns to baseline after pulp_post_return.
//
//go:wasmexport probe_alloc_live
func probeAllocLive() uint32 { return pulp.AllocLive() }

type Engine uint8

const (
	Vanilla Engine = iota
	Paper
	Fabric
	Bedrock
)

type ResolveRequest struct {
	Engine      Engine
	Version     *string
	ModsJson    *string
	DatapackIds *string
}

type EnvVar struct {
	Key   string
	Value string
}

type ResolveResponse struct {
	ServerJarUrl string
	Plugins      []string
	Mods         []string
	Datapacks    []string
	CpuWeight    float64
	RamWeightMb  float64
	EnvOverrides []EnvVar
}

// ---- raw linear-memory access (little-endian, wasm32) ----

func writeU8(a uint32, v uint8)   { *(*uint8)(unsafe.Pointer(uintptr(a))) = v }
func writeU32(a uint32, v uint32) { *(*uint32)(unsafe.Pointer(uintptr(a))) = v }
func writeU64(a uint32, v uint64) { *(*uint64)(unsafe.Pointer(uintptr(a))) = v }
func readU8(a uint32) uint8       { return *(*uint8)(unsafe.Pointer(uintptr(a))) }
func readU32(a uint32) uint32     { return *(*uint32)(unsafe.Pointer(uintptr(a))) }

func liftStringAt(ptr, length uint32) string {
	if length == 0 {
		return ""
	}
	return string(unsafe.Slice((*byte)(unsafe.Pointer(uintptr(ptr))), length))
}

// liftStringSlot reads a (ptr,len) string header at addr.
func liftStringSlot(a uint32) string { return liftStringAt(readU32(a+0), readU32(a+4)) }

func lowerString(str string) (ptr, length uint32) {
	if len(str) == 0 {
		return 0, 0
	}
	p := pulp.Alloc(uint32(len(str)))
	dst := unsafe.Slice((*byte)(unsafe.Pointer(uintptr(p))), len(str))
	copy(dst, str)
	return p, uint32(len(str))
}

// writeStringSlot lowers str and writes its (ptr,len) header at addr.
func writeStringSlot(a uint32, str string) {
	p, l := lowerString(str)
	writeU32(a+0, p)
	writeU32(a+4, l)
}

func freeStringSlot(a uint32) { pulp.Free(readU32(a + 0)) }

// liftOption_string reads option<string> (disc@+0, payload@+4).
func liftOption_string(a uint32) *string {
	if readU8(a+0) == 0 {
		return nil
	}
	v := liftStringSlot(a + 4)
	return &v
}

// liftRequest decodes ResolveRequest (align 4, size 40) from the args buffer.
func liftRequest(argsPtr uint32) ResolveRequest {
	return ResolveRequest{
		Engine:      Engine(readU8(argsPtr)),
		Version:     liftOption_string(argsPtr + 4),
		ModsJson:    liftOption_string(argsPtr + 16),
		DatapackIds: liftOption_string(argsPtr + 28),
	}
}

// lower_list_string allocates n*8 and writes each element.
func lower_list_string(xs []string) (ptr, length uint32) {
	n := uint32(len(xs))
	if n == 0 {
		return 0, 0
	}
	base := pulp.Alloc(n * 8)
	for i := range xs {
		slot := base + uint32(i)*8
		writeStringSlot(slot, xs[i])
	}
	return base, n
}

// lower_list_EnvVar allocates n*16 and writes each element.
func lower_list_EnvVar(xs []EnvVar) (ptr, length uint32) {
	n := uint32(len(xs))
	if n == 0 {
		return 0, 0
	}
	base := pulp.Alloc(n * 16)
	for i := range xs {
		slot := base + uint32(i)*16
		writeStringSlot(slot, xs[i].Key)
		writeStringSlot(slot+8, xs[i].Value)
	}
	return base, n
}

// lowerResult encodes result<ResolveResponse, string> (align 8, size 64).
func lowerResult(resp ResolveResponse, err error) uint32 {
	rec := pulp.Alloc(64) // zero-filled
	if err != nil {
		writeU8(rec+0, 1)
		writeStringSlot(rec+8, err.Error())
		return rec
	}
	writeU8(rec+0, 0)
	writeStringSlot(rec+8, resp.ServerJarUrl)
	{
		p, l := lower_list_string(resp.Plugins)
		writeU32(rec+16+0, p)
		writeU32(rec+16+4, l)
	}
	{
		p, l := lower_list_string(resp.Mods)
		writeU32(rec+24+0, p)
		writeU32(rec+24+4, l)
	}
	{
		p, l := lower_list_string(resp.Datapacks)
		writeU32(rec+32+0, p)
		writeU32(rec+32+4, l)
	}
	writeU64(rec+40, math.Float64bits(resp.CpuWeight))
	writeU64(rec+48, math.Float64bits(resp.RamWeightMb))
	{
		p, l := lower_list_EnvVar(resp.EnvOverrides)
		writeU32(rec+56+0, p)
		writeU32(rec+56+4, l)
	}
	return rec
}

func free_list_string(a uint32) {
	base := readU32(a + 0)
	n := readU32(a + 4)
	for i := uint32(0); i < n; i++ {
		slot := base + i*8
		freeStringSlot(slot)
	}
	pulp.Free(base)
}

func free_list_EnvVar(a uint32) {
	base := readU32(a + 0)
	n := readU32(a + 4)
	for i := uint32(0); i < n; i++ {
		slot := base + i*16
		freeStringSlot(slot)
		freeStringSlot(slot + 8)
	}
	pulp.Free(base)
}

// pulp_post_return tree-frees the whole result<> record the host just lifted:
// top record + every string / list sub-buffer pinned during lowerResult.
//
//go:wasmexport pulp_post_return
func pulpPostReturn(recPtr, recLen uint32) {
	_ = recLen
	if recPtr == 0 {
		return
	}
	if readU8(recPtr+0) == 0 { // ok arm
		freeStringSlot(recPtr + 8)
		free_list_string(recPtr + 16)
		free_list_string(recPtr + 24)
		free_list_string(recPtr + 32)
		free_list_EnvVar(recPtr + 56)
	} else { // err arm
		freeStringSlot(recPtr + 8)
	}
	pulp.Free(recPtr)
}

// rawResolve is the pulp.RawProvider registered for "resolve": it lifts the
// request from linear memory, runs the typed handler, lowers the result as a
// pinned pointer tree, and writes the (respPtr, respLen) out-params.
func rawResolve(argsPtr, argsLen, respPtrOut, respLenOut uint32) uint32 {
	_ = argsLen
	req := liftRequest(argsPtr)
	resp, err := resolve(req)
	rec := lowerResult(resp, err)
	writeU32(respPtrOut, rec)
	writeU32(respLenOut, 64)
	return 0
}
